# Generated by Django 5.2.9 on 2025-12-18 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_userprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('none', 'None'), ('loan_ask_installments', 'Loan ask installments'), ('loan_ask_first_due', 'Loan ask first due')], default='none', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_conversation', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('telegram_chat_id', models.BigIntegerField()),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['telegram_user_id'], name='bot_telegra_telegra_1f0405_idx')],
            },
        ),
    ]
