# Generated by Django 5.2.9 on 2025-12-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('owner', 'Owner'), ('finance', 'Finanzas'), ('support', 'Soporte')], default='user', max_length=20),
        ),
    ]
