# Generated by Django 5.2.9 on 2025-12-18 xx:xx
from django.conf import settings
from django.db import migrations

ROLE_ADMIN = "admin_general"
ROLE_FINANCE = "finance"
ROLE_SUPPORT = "support"


def forwards(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    UserProfile = apps.get_model("accounts", "UserProfile")

    # 1) asegurar groups
    g_admin, _ = Group.objects.get_or_create(name=ROLE_ADMIN)
    g_fin, _ = Group.objects.get_or_create(name=ROLE_FINANCE)
    g_sup, _ = Group.objects.get_or_create(name=ROLE_SUPPORT)

    # 2) migrar role (legacy) -> groups
    for prof in UserProfile.objects.select_related("user").all():
        user = prof.user

        # OJO: role existe en DB ahora mismo (0003), así que esto funciona
        role = getattr(prof, "role", None)

        if role in ("owner", ROLE_ADMIN):
            user.groups.add(g_admin)
        elif role == ROLE_FINANCE:
            user.groups.add(g_fin)
        elif role == ROLE_SUPPORT:
            user.groups.add(g_sup)


def backwards(apps, schema_editor):
    # No recreamos el campo role ni revertimos grupos aquí.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
    ]