# Generated by Django 5.2.9 on 2025-12-18 16:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], default='expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('CLP', 'CLP'), ('USD', 'USD')], default='CLP', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='telegram', max_length=20)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='transaction_user_id_06f072_idx'), models.Index(fields=['user', 'kind', 'occurred_at'], name='transaction_user_id_ca7e0e_idx')],
            },
        ),
    ]
