# Generated by Django 5.2.9 on 2025-12-18 18:19

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_uniq_tx_user_telegram_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
       
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='amount_original',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='currency',
            new_name='currency_original',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_base',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='base_currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_clp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'currency_original', 'occurred_at'], name='transaction_user_id_368b45_idx'),
        ),
    ]
