# Generated by Django 5.2.9 on 2025-12-18 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transaction_uniq_transaction_user_telegram_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14),
        ),
    ]
