# Generated by Django 5.2.9 on 2025-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_billingsettings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='billing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='go_live_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
