# Generated by Django 5.2.9 on 2025-12-18 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('lent', 'Presté (me deben)'), ('borrowed', 'Me prestaron (yo debo)')], max_length=12)),
                ('person_name', models.CharField(max_length=120)),
                ('principal_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_original', models.CharField(choices=[('CLP', 'CLP'), ('USD', 'USD')], default='CLP', max_length=3)),
                ('principal_clp', models.DecimalField(decimal_places=0, max_digits=16)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('first_due_date', models.DateField(blank=True, null=True)),
                ('installments_count', models.PositiveIntegerField(default=1)),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal')], default='monthly', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('closed', 'Cerrado'), ('canceled', 'Cancelado')], default='active', max_length=10)),
                ('telegram_origin_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_original', models.CharField(choices=[('CLP', 'CLP'), ('USD', 'USD')], default='CLP', max_length=3)),
                ('amount_clp', models.DecimalField(decimal_places=0, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('overdue', 'Atrasada')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount_original', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('paid_amount_clp', models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
            options={
                'ordering': ('due_date', 'n'),
            },
        ),
        migrations.CreateModel(
            name='LoanAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('due_today', 'Vence hoy'), ('due_soon', 'Vence pronto'), ('overdue', 'Atrasada')], max_length=20)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='telegram', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='loans.loaninstallment')),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status'], name='loans_loan_user_id_d0fb34_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'person_name'], name='loans_loan_user_id_80122b_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['loan', 'status'], name='loans_loani_loan_id_70533c_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['due_date', 'status'], name='loans_loani_due_dat_f5abcd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loaninstallment',
            unique_together={('loan', 'n')},
        ),
        migrations.AddIndex(
            model_name='loanalertlog',
            index=models.Index(fields=['installment', 'alert_type', 'channel'], name='loans_loana_install_ceae07_idx'),
        ),
        migrations.AddIndex(
            model_name='loanalertlog',
            index=models.Index(fields=['sent_at'], name='loans_loana_sent_at_5ee33d_idx'),
        ),
    ]
