# Generated by Django 5.2.9 on 2025-12-19 23:06

import budgets.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('match_keywords', models.CharField(blank=True, default='', help_text='Palabras clave separadas por coma para estimar gasto por descripción.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget category',
                'verbose_name_plural': 'Budget categories',
                'ordering': ['name', 'id'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=budgets.models.month_start)),
                ('amount_clp', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='budgets.budgetcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly budget',
                'verbose_name_plural': 'Monthly budgets',
                'ordering': ['-month', 'category__name', '-id'],
                'unique_together': {('user', 'category', 'month')},
            },
        ),
    ]
