# Generated by Django 5.2.9 on 2025-12-22 14:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('bank', models.CharField(blank=True, default='', max_length=80, verbose_name='Banco')),
                ('brand', models.CharField(blank=True, default='', max_length=40, verbose_name='Marca')),
                ('last4', models.CharField(blank=True, default='', max_length=4, verbose_name='Últimos 4')),
                ('currency', models.CharField(default='CLP', max_length=10, verbose_name='Moneda')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Límite / cupo')),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que inicia el ciclo (corte). Ej: 5, 10, 25.', verbose_name='Día de corte')),
                ('due_day', models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que pagas la tarjeta. Ej: 1, 15, 28.', verbose_name='Día de pago')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['-is_active', 'name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='cards_card_user_id_e146f9_idx')],
            },
        ),
    ]
