# Generated by Django 5.2.9 on 2025-12-22 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('transactions', '0007_transaction_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('suggested_currency', models.CharField(default='CLP', max_length=3)),
                ('suggested_date', models.DateField(blank=True, null=True)),
                ('suggested_merchant', models.CharField(blank=True, default='', max_length=255)),
                ('suggested_description', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confirmed_currency', models.CharField(blank=True, default='', max_length=3)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('confirmed_description', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.card')),
                ('created_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
